### ISSUE TITLE
java.lang.NoSuchFieldError: id_RSASSA_PSS_SHAKE128

### ISSUE THREAD

**Issue by RichLoli** [hyperledger/fabric-gateway-java#95]
Use fabric-gateway-java to connect Fabric BlockChain throw this error:
```

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.hyperledger.fabric.gateway.Network]: Circular reference involving containing bean 'fabricConf' - consider declaring the factory method as static for independence from its containing instance. Factory method 'gainNetwork' threw exception; nested exception is java.lang.NoSuchFieldError: id_RSASSA_PSS_SHAKE128
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.1.jar!/:5.3.1]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.3.1.jar!/:5.3.1]
        ... 41 common frames omitted
Caused by: java.lang.NoSuchFieldError: id_RSASSA_PSS_SHAKE128
        at org.bouncycastle.operator.DefaultSignatureNameFinder.<clinit>(Unknown Source) ~[bcpkix-jdk15on-1.70.jar!/:1.70.00.0]
        at org.bouncycastle.operator.jcajce.OperatorHelper.<clinit>(Unknown Source) ~[bcpkix-jdk15on-1.70.jar!/:1.70.00.0]
        at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.<init>(Unknown Source) ~[bcpkix-jdk15on-1.70.jar!/:1.70.00.0]
        at org.hyperledger.fabric.sdk.security.certgen.TLSCertificateBuilder.createSelfSignedCertificate(TLSCertificateBuilder.java:125) ~[fabric-sdk-java-2.2.11.jar!/:na]
        at org.hyperledger.fabric.sdk.security.certgen.TLSCertificateBuilder.createCert(TLSCertificateBuilder.java:99) ~[fabric-sdk-java-2.2.11.jar!/:na]
        at org.hyperledger.fabric.sdk.security.certgen.TLSCertificateBuilder.clientCert(TLSCertificateBuilder.java:78) ~[fabric-sdk-java-2.2.11.jar!/:na]
        at org.hyperledger.fabric.sdk.Channel.addPeer(Channel.java:668) ~[fabric-sdk-java-2.2.11.jar!/:na]
        at org.hyperledger.fabric.gateway.impl.GatewayImpl.getNetwork(GatewayImpl.java:245) ~[fabric-gateway-java-2.2.0.jar!/:na]
        at com.example.czdemo.config.FabricConf.gainNetwork(FabricConf.java:77) ~[classes!/:0.0.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.1.jar!/:5.3.1]
        ... 42 common frames omitted
```
Use Centos 7.5 OS

**Comment by bestbeforetoday** [comment]
That exception looks to have occurred within the constructor for `org.bouncycastle.operator.jcajce.JcaContentSignerBuilder`. This doesn't look to me to be something obviously caused by the SDK. It seems to be some other environmental, configuration or class-loading issue affecting the the class initialisation of `org.bouncycastle.operator.DefaultSignatureNameFinder` where it populates its map of object identifiers to algorithm names. The field it is failing to find is `org.bouncycastle.asn1.cms.CMSObjectIdentifiers.id_RSASSA_PSS_SHAKE128`.

In my local environment, the `org.bouncycastle.asn1.cms.CMSObjectIdentifiers.id_RSASSA_PSS_SHAKE128` field does exist in the `org.bouncycastle:bcutil-jdk15on:1.70` package.

**Comment by RichLoli** [comment]
> 

Thanks! The issues is already be fix , Caused by conflicts with other SDK dependencies
